language: php

dist: trusty

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

sudo: false

install:
  - composer install
  - ./vendor/bin/simple-phpunit install

script: ./vendor/bin/simple-phpunit -v --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi'