on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ 7.3, 7.4 ]
        symfony: [ 3.4, 4.4, 5.2 ]
        include:
          - php: 8.0
            symfony: 5.2
          - php: 8.1
            symfony: 5.2
            experimental: true
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@2.9.0
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: zip, :xdebug
          tools: composer

      - name: Determine composer cache directory
        id: composer-cache
        run: echo "::set-output name=directory::$(composer config cache-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2.1.3
        with:
          path: ${{ steps.composer-cache.outputs.directory }}
          key: ${{ matrix.php }}-${{ matrix.symfony }}-composer-
          restore-keys: ${{ matrix.php }}-${{ matrix.symfony }}-composer-

      - name: Install dependencies
        run: |
          echo "::group::composer update"
          composer require symfony/symfony:${{ matrix.symfony }}.* --no-update
          composer update --no-interaction --prefer-dist
          echo "::endgroup::"

      - name: Run PHPUnit
        run: ./vendor/bin/simple-phpunit -v